#!/bin/bash

echo "Creating user(${EHRBASE_USER}) pass(${EHRBASE_PASSWORD}) db(ehrbase)"

psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" <<-EOSQL
CREATE ROLE ${EHRBASE_USER} WITH LOGIN PASSWORD '${EHRBASE_PASSWORD}';
CREATE DATABASE ehrbase ENCODING 'UTF-8' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE ehrbase TO ${EHRBASE_USER};
CREATE USER root WITH SUPERUSER;
EOSQL
